#!/bin/bash

readme=README.md

set -e


dzil build
pod2markdown < Time-Ago-*/lib/Time/Ago.pm > $readme

cat << EOT >> $readme

[![Build Status](https://travis-ci.org/mla/time-ago.svg?branch=master)](https://travis-ci.org/mla/time-ago)
EOT
